name: Lint Readme

on: [pull_request, push]

jobs:
  lint_readme:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell
      - run: codespell
